### PR TITLE
Port useful changes from @camwest's fork

### PR DESCRIPTION
**Pull request by stevemao**
@camwest would you mind giving me the npm push access to the module and can we release from this repo?

### CODE REVIEW

**Comment by stevemao** [comment]
I would like to make a new release after this is merged 😄

**Comment by camwest** [comment]
@stevemao what's your npm username?

**Comment by stevemao** [comment]
stevemao, same as GitHub

**Comment by camwest** [comment]
done

**Comment by stevemao** [comment]
Thank you so much :)

**Pull request merged**
