### PR TITLE
Cache for very common cases

### PR DESCRIPTION
**Pull request by benjamingr**
I estimate that the majority of people who left pad use it for formatting in which case performing any calculations at all is silly.

This should give an additional boost after the changes that were merged from my PR against the old repo today :)

### CODE REVIEW

**Comment by stevemao** [comment]
Thanks @benjamingr , would you also fix the benchmark you mentioned?

**Comment by nicbou** [comment]
As commented in the pull request:

Is there any reason to believe that this will improve performance in any way?

**Comment by benjamingr** [comment]
@nicbou yes, if you check my original pull request to the original left-pad there are benchmarks that I should port.

It is always faster to cache strings and not calculate them - this is a very common use case for left-pad.

**Comment by nicbou** [comment]
I have looked, but I cannot find it

**Pull request merged**
