### PR TITLE
convert string using .toString()

### PR DESCRIPTION
**Pull request by alkuhar**
Using .toString() to convert str to string

### CODE REVIEW

**Comment by stevemao** [comment]
Reasons?

**Comment by alkuhar** [comment]
Based on my testing I found that .toString was a bit faster.

**Comment by alkuhar** [comment]
Also it throws an error if a false positive was passed such as null or undefined.

**Comment by stevemao** [comment]
I don't think it'd be faster.

> Also it throws an error if a false positive was passed such as null or undefined.

This is not the correct way of checking type. Also do we want to throw here?

**Comment by alkuhar** [comment]
> This is not the correct way of checking type. Also do we want to throw here?

Maybe you could do a type check in the beginning?

`typeof str === "undefined" ? console.log(str) : str = str + '';`

**Comment by stevemao** [comment]
What's your use case? Why do you want to check the type?

**Comment by alkuhar** [comment]
I wanted to assign strings to an array and then print them with 2 spaces on the left. I guess I could implement type checking when assigning to the array.

**Comment by cloned2k16** [comment]
while I don't think using toString() is  a good idea ...  
(it will unnecessarily crash where otherwise you'll only get a ugly result ...
(which is anyway straightforward))

the order used right now it's probably slower than the other way around ...
cause, the interpreter,
 will try to guess the type of the result operation by the type of the first operand, so ..

Integer + String will end up anyway as a String ... 
but in first place, 
the interpreter would guess that it have to add Integers (or numbers anyway) 
then it falls back (once realized that the second is an empty String)
  and finally use  Integer.toString() + emptyString

aside from that alone ...  
( '' + whatever) ...  is much more clear and elegant than the other way around ..
when the purpose is to convert something to string ..

and with very high probability ... faster too ...

**Comment by stevemao** [comment]
`+ ''` is definitely faster. @alkuhar is probably arguing if it should throw on `null` or `undefined`.

**Comment by alkuhar** [comment]
Yeah, it might be okay just to return `null` or `undefined` instead of throw an error.

**Comment by stevemao** [comment]
Doesn't look like we got many supports here. Closing. Feel free to argue :)

**Pull request closed without merging**
